import Notification from "@/components/global/Notification";
import { Providers } from "@/redux/provider";

export const metadata = {
  title: "Vendor Management System",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Providers>
        <body>{children}</body>
        <Notification />
      </Providers>
    </html>
  );
}
