export const tableHeaders = [
  "Order ID",
  "Customer Name",
  "Date",
  "Payment Status",
  "Fulfillment Status",
  "Delivery Status",
  "Delivery Method",
  "Channel",
  "Market",
  "Num of Products",
  "Amount",
  "Actions",
];

export const ordersData = [
  {
    orderId: 1,
    amount: 100,
    customerName: "John Doe",
    customerPhone: "1234567890",
    customerEmail: "john@example.com",
    numOfProducts: 9,
    date: "2022-05-01",
    paymentStatus: "Paid",
    fulfillmentStatus: "Fulfilled",
    deliveryStatus: "Delivered",
    deliveryMethod: "Express",
    channel: "Online",
    market: "Global",
  },
  {
    orderId: 4,
    amount: 100,
    customerName: "Fahad Kazmi",
    customerPhone: "123456",
    customerEmail: "doe@example.com",
    numOfProducts: 37,
    date: "2022-04-01",
    paymentStatus: "Paid",
    fulfillmentStatus: "Fulfilled",
    deliveryStatus: "Delivered",
    deliveryMethod: "Express",
    channel: "Online",
    market: "Global",
  },
  {
    orderId: 2,
    amount: 100,
    customerName: "naveed",
    customerPhone: "1234567890",
    customerEmail: "oe@example.com",
    numOfProducts: 33,
    date: "2022-03-01",
    paymentStatus: "Paid",
    fulfillmentStatus: "Fulfilled",
    deliveryStatus: "Delivered",
    deliveryMethod: "Express",
    channel: "Online",
    market: "Global",
  },
  {
    orderId: 3,
    amount: 100,
    customerName: "Muzamil",
    customerPhone: "1234567890",
    customerEmail: "john.doe@example.com",
    numOfProducts: 2,
    date: "2022-02-01",
    paymentStatus: "Pending",
    fulfillmentStatus: "Fulfilled",
    deliveryStatus: "Delivered",
    deliveryMethod: "Express",
    channel: "Online",
    market: "Global",
  },
];
